apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: localhost/systemadminone-restaurant-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5004
        env:
        - name: CONNECTION_STRING
          value: "mongodb+srv://dinuka:1234@cluster0.zdovbfd.mongodb.net/bigBite?retryWrites=true&w=majority&appName=Cluster0"
        - name: JWT_SECRET
          value: "sliitit"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: NodePort
  selector:
    app: restaurant-service
  ports:
  - port: 5004
    targetPort: 5004
    nodePort: 30504
